AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/VariableNumber:
  Exclude:
    - 'spec/features/exe/{quake_game_report,quake_game_death_cause}_spec.rb'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
