name: Publish on RubyGems

on:
  release:
    types: [published]

env:
  GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: gem build quake_game.gemspec
      - run: gem push quake_game-*.gem --key $GEM_HOST_API_KEY

